# Generated by Django 3.0.5 on 2020-11-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20201101_1824'),
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('type_expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.TypeExpenses')),
            ],
        ),
    ]
