# Generated by Django 3.0.5 on 2020-11-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_mcc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcc',
            name='description',
        ),
    ]
