# Generated by Django 3.0.5 on 2021-01-31 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('factory', '0004_bankstatementsdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementsdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
