# Generated by Django 3.0.5 on 2022-10-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
