# Generated by Django 3.0.5 on 2022-11-05 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_bankstatements_bank'),
        ('factory', '0008_auto_20221030_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementsdata',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Bank'),
        ),
    ]
