# Generated by Django 3.0.5 on 2022-11-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_merchant'),
        ('factory', '0009_bankstatementsdata_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.Bank'),
            preserve_default=False,
        ),
    ]
