# Generated by Django 3.0.5 on 2020-10-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=50)),
                ('index', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('index', models.PositiveIntegerField(null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_place', models.CharField(max_length=200)),
                ('sum_transaction', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_of_trans', models.DateTimeField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Countries')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Currency')),
                ('type_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Places')),
                ('type_transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.MoneyTransaction')),
            ],
        ),
    ]
