# Generated by Django 3.0.5 on 2020-10-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
