# Generated by Django 3.0.5 on 2020-10-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='abbreviation',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
