# Generated by Django 3.0.5 on 2020-10-31 16:55

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20201030_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransaction',
            old_name='type_transaction',
            new_name='type_transaction_en',
        ),
        migrations.AddField(
            model_name='moneytransaction',
            name='type_transaction_ua',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
