# Generated by Django 3.0.5 on 2020-10-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20201031_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatements',
            name='date_of_trans',
            field=models.DateField(null=True),
        ),
    ]
