# Generated by Django 3.0.5 on 2020-10-31 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20201031_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatements',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
