# Generated by Django 3.0.5 on 2020-10-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_bankstatements_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_expenses_ua', models.CharField(max_length=100)),
                ('type_expenses_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='places',
            old_name='type_place',
            new_name='type_place_en',
        ),
        migrations.AddField(
            model_name='places',
            name='type_place_ua',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
