# Generated by Django 3.0.5 on 2020-11-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20201101_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransaction',
            name='type_transaction_ru',
            field=models.CharField(max_length=50, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='type_transaction_ua',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
