# Generated by Django 3.0.5 on 2020-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20201101_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='country',
            new_name='country_ru',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='index_c',
            new_name='iso',
        ),
        migrations.AddField(
            model_name='countries',
            name='abbreviation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='country_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='country_ua',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='type_transaction_ua',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
