# Generated by Django 3.0.5 on 2020-11-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20201101_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatements',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Countries'),
        ),
        migrations.AlterField(
            model_name='bankstatements',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Currency'),
        ),
    ]
