# Generated by Django 3.0.5 on 2021-02-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_auto_20210201_2106'),
        ('finance', '0020_auto_20210201_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatements',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.BankStatementsData'),
        ),
    ]
