# Generated by Django 3.0.5 on 2022-11-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='short_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
