# Generated by Django 3.0.5 on 2020-11-15 20:29

from django.db import migrations, models
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grafic_matplotlib', '0002_pie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
    ]
